<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASM gen\Kernel.Contracts\Kernel.Contracts.csproj" />
    <ProjectReference Include="..\Kernel.Common\Kernel.Common.csproj" />
  </ItemGroup>

</Project>
