<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Compiller\Compiller.csproj" />
	<ProjectReference Include="..\Kernel.Common\Kernel.Common.csproj" />
	<ProjectReference Include="..\Kernel\Kernel.csproj" />
  </ItemGroup>

</Project>
